#! /bin/sh

# Wait until the processes are actually killed
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x feh >/dev/null; do sleep 1; done

# Monitor Layout
bspc monitor -d I II III IV V

bspc config border_width 1
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a firefox desktop='^2' follow=on

# -- AUTOSTART --
# Keybindings
sxhkd &
picom &
# Cursor
xsetroot -cursor_name left_ptr

~/.config/polybar/launch.sh &
# dunst
dunst -conf $HOME/.config/dunst/dunstrc &

feh --bg-fit ~/Pictures/01.jpg &
