#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_motion_interval       5
bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Set Wallpaper
feh --bg-center .config/bspwm/wallpaper/01.jpg
