#!/usr/bin/bash

# Define the path to your sxhkd configuration file.
# It's good practice to make this configurable or use a standard path.
SXHKD_CONFIG="${HOME}/.config/sxhkd/sxhkdrc"
ROFI_THEME="$HOME/.config/rofi/config-commons.rasi"

# Check if the sxhkdrc file exists.
if [[ ! -f "${SXHKD_CONFIG}" ]]; then
  echo "Error: sxhkd config file not found at ${SXHKD_CONFIG}" >&2
  exit 1
fi

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' "${SXHKD_CONFIG}" |
  column -t -s $'\t' | rofi -dmenu -i -markup-rows -no-show-icons -theme "$ROFI_THEME"

