[config]

[templates.hyprland]
input_path = "~/.config/matugen/templates/hypr/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hypr/hyprlock-colors.conf"
output_path = "~/.config/hypr/colors-hyprlock.conf"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk/gtk3.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk/gtk4.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell/colors.json"
output_path = "~/.cache/quickshell/colors.json"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty/colors.conf"
output_path = "~/.config/kitty/themes/matugen.conf"

[templates.quickshell-qml]
input_path = "~/.config/matugen/templates/quickshell/colors.qml"
output_path = "~/.cache/quickshell/Colors.qml"

[templates.preview_picker]
input_path = "~/.config/matugen/templates/hyprland-preview-share-picker/style.css.template"
output_path = "~/.config/hyprland-preview-share-picker/style.css"
