[config]

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi/colors.rasi"
output_path = "~/.config/matugen/output/rofi-colors.rasi"

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar/colors.css'
output_path = '~/.config/matugen/output/waybar-colors.css'

[templates.gen_lua]
input_path = "~/.config/matugen/templates/hypr/hyprland-colors.lua"
output_path = "~/.config/matugen/output/hypr-colors.lua"

[templates.gen_lock]
input_path = "~/.config/matugen/templates/hypr/hyprlock-colors.conf"
output_path = "~/.config/matugen/output/hyprlock-colors.conf"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk/gtk3.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk/gtk4.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell/colors.json"
output_path = "~/.cache/quickshell/colors.json"
