
wallpaper {
    monitor = eDP-1
    path = /home/jllyn/Pictures/catppuccin.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/jllyn/Pictures/catppuccin.png
    fit_mode = cover
}

splash = false
ipc = on

