-- Generated by nwg-displays on 2026-05-31 at 23:17:15. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.01",
    position = "0x1080",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
