hl.on("hyprland.start", function()
  hl.exec_cmd("uwsm app -- qs")
  hl.exec_cmd("uwsm app -- hyprpaper")
  hl.exec_cmd("uwsm app -- ~/.config/quickshell/helpers/battery_daemon")
  hl.exec_cmd("dbus-update-activation-environment --all")
  hl.exec_cmd("uwsm app -- /usr/lib/hyprpolkitagent/hyprpolkitagent")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  hl.exec_cmd("uwsm app -- ~/.config/hypr/scripts/usb-monitor.sh")
  hl.exec_cmd("uwsm app -- ~/.config/quickshell/helpers/mtp_notify")
  hl.exec_cmd("uwsm app -- udiskie --notify")
  hl.exec_cmd("uwsm app -- ~/.config/hypr/scripts/idle-inhibit.sh")
  hl.exec_cmd("uwsm app -- easyeffects --hide-window --service-mode")
  hl.exec_cmd("uwsm app -- hypridle")
  hl.exec_cmd("uwsm app -- ~/.config/hypr/scripts/cliphist.sh store")
end)
