#!/usr/bin/env bash
set -uo pipefail

THEME_DIR="$HOME/.themes/Primo"
COLORS_FILE="$HOME/.config/gtk-3.0/colors.css"

log() { [[ "${VERBOSE:-false}" == "true" ]] && echo "[Primo] $*"; }

if [[ ! -f "$COLORS_FILE" ]]; then
    echo "Error: $COLORS_FILE not found. Run theme_switcher first." >&2
    exit 1
fi

log "Building Primo theme..."

mkdir -p "$THEME_DIR/gtk-3.0" "$THEME_DIR/gtk-4.0"

log "Generating GTK3 styles..."
cat > "$THEME_DIR/gtk-3.0/gtk.css" << 'EOF'
@import url("colors.css");

/* ═══════════════════════════════════════════════
   Primo GTK3 Theme — generated by rebuild_primo.sh
   ═══════════════════════════════════════════════ */

/* ── Global Reset ──────────────────────────── */
* {
    background-clip: padding-box;
    -gtk-outline-radius: 6px;
    outline-color: alpha(@fg_color, 0.15);
    outline-style: solid;
    outline-width: 0;
    outline-offset: -4px;
}

/* ── Window ────────────────────────────────── */
window.background, .window-frame {
    background-color: @base_color;
    color: @fg_color;
}

window.background.csd {
    border-radius: 0;
}

/* ── Base States ───────────────────────────── */
*:disabled {
    -gtk-icon-effect: dim;
    color: alpha(@fg_color, 0.4);
}

.dim-label {
    color: alpha(@fg_color, 0.6);
}

separator {
    background-color: @border_color;
}

/* ── Entries & Spinbuttons ─────────────────── */
entry, spinbutton {
    min-height: 34px;
    padding: 0 8px;
    border-radius: 6px;
    caret-color: currentColor;
    background-color: alpha(@fg_color, 0.06);
    color: @fg_color;
    border: 1px solid @border_color;
    transition: border-color 120ms ease, background-color 120ms ease;
}

entry:focus, spinbutton:focus {
    border-color: @primary_color;
    background-color: alpha(@primary_color, 0.06);
}

entry:disabled, spinbutton:disabled {
    background-color: alpha(@fg_color, 0.03);
    color: alpha(@fg_color, 0.4);
    border-color: alpha(@border_color, 0.4);
}

entry selection, spinbutton selection {
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}

entry.search-entry {
    border-radius: 6px;
    padding: 3px 8px;
}

/* ── Buttons ───────────────────────────────── */
button {
    min-height: 24px;
    min-width: 16px;
    padding: 5px 9px;
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.07);
    color: @fg_color;
    border: 1px solid @border_color;
    transition: all 120ms ease;
}

button:hover {
    background-color: alpha(@primary_color, 0.12);
    border-color: alpha(@primary_color, 0.3);
}

button:active {
    background-color: alpha(@primary_color, 0.18);
}

button:checked {
    background-color: alpha(@primary_color, 0.25);
    color: @primary_color;
    border-color: alpha(@primary_color, 0.4);
}

button:disabled {
    background-color: alpha(@fg_color, 0.03);
    color: alpha(@fg_color, 0.4);
    border-color: alpha(@border_color, 0.3);
}

button:focus {
    border-color: @primary_color;
}

button.flat {
    background-color: transparent;
    border-color: transparent;
}

button.flat:hover {
    background-color: alpha(@fg_color, 0.07);
}

button.suggested-action {
    background-color: @primary_color;
    color: @selected_fg_color;
    border-color: @primary_color;
}

button.suggested-action:hover {
    background-color: alpha(@primary_color, 0.85);
}

button.destructive-action {
    background-color: @error_color;
    color: @selected_fg_color;
    border-color: @error_color;
}

button.destructive-action:hover {
    opacity: 0.85;
}

/* ── Linked Buttons ────────────────────────── */
.linked > button, .linked > spinbutton, .linked > entry {
    border-radius: 0;
}

.linked > button:first-child {
    border-top-left-radius: 6px;
    border-bottom-left-radius: 6px;
}

.linked > button:last-child {
    border-top-right-radius: 6px;
    border-bottom-right-radius: 6px;
}

.linked > button:only-child {
    border-radius: 6px;
}

/* ── Headerbar / Titlebar ──────────────────── */
headerbar, .titlebar {
    min-height: 40px;
    padding: 0 8px;
    background-color: alpha(@bg_color, 0.95);
    color: @fg_color;
    border-bottom: 1px solid @border_color;
}

headerbar button, .titlebar button {
    border-color: transparent;
    background-color: transparent;
}

headerbar button:hover, .titlebar button:hover {
    background-color: alpha(@fg_color, 0.1);
}

headerbar button:checked, .titlebar button:checked {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

/* ── Menu Bar ──────────────────────────────── */
.menu-bar {
    background-color: alpha(@bg_color, 0.95);
    border-bottom: 1px solid @border_color;
}

.menu-bar button {
    background: transparent;
    border: none;
    padding: 2px 8px;
    transition: background-color 120ms ease;
}

.menu-bar button:hover {
    background-color: alpha(@fg_color, 0.1);
}

/* ── Toolbar ───────────────────────────────── */
.toolbar {
    background-color: alpha(@bg_color, 0.9);
    border-bottom: 1px solid @border_color;
    padding: 2px 4px;
}

.toolbar button {
    margin: 1px;
    padding: 3px 8px;
    border-radius: 6px;
    transition: all 120ms ease;
}

.toolbar button:hover {
    background-color: alpha(@primary_color, 0.12);
}

.inline-toolbar {
    background-color: alpha(@bg_color, 0.9);
    padding: 6px;
    border: none;
}

/* ── Location / Path Bar ───────────────────── */
.location-bar {
    background-color: alpha(@bg_color, 0.95);
    border-bottom: 1px solid @border_color;
    padding: 2px 4px;
}

.path-bar button {
    background: transparent;
    border: none;
    padding: 3px 10px;
    margin: 1px 0;
    transition: all 120ms ease;
}

.path-bar button:hover {
    background-color: alpha(@fg_color, 0.1);
}

.path-bar button:checked {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

/* ── Sidebar ───────────────────────────────── */
.sidebar {
    background-color: alpha(@base_color, 0.95);
    border-right: 1px solid @border_color;
}

.sidebar .view {
    background-color: transparent;
    border: none;
}

.sidebar .view:not(:selected):hover {
    background-color: alpha(@fg_color, 0.07);
}

.sidebar .view:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
    font-weight: 600;
}

placessidebar row {
    min-height: 28px;
    padding: 4px 8px;
    border-radius: 6px;
}

placessidebar row:hover {
    background-color: alpha(@fg_color, 0.07);
}

placessidebar row:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

/* ── Column Headers ────────────────────────── */
column-header button {
    background-color: alpha(@bg_color, 0.8);
    border: none;
    border-bottom: 1px solid @border_color;
    border-right: 1px solid @border_color;
    padding: 4px 8px;
    font-weight: 600;
    border-radius: 0;
}

column-header button:hover {
    background-color: alpha(@fg_color, 0.07);
    border-bottom-color: @primary_color;
}

/* ── Tree / List View ──────────────────────── */
treeview.view {
    background-color: @base_color;
    color: @fg_color;
}

treeview.view:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

treeview.view:not(:selected):hover {
    background-color: alpha(@fg_color, 0.05);
}

treeview.view separator {
    background-color: @border_color;
}

/* ── Icon View ─────────────────────────────── */
iconview {
    background-color: @base_color;
    color: @fg_color;
}

iconview:selected {
    background-color: alpha(@primary_color, 0.25);
}

iconview:hover:not(:selected) {
    background-color: alpha(@fg_color, 0.05);
}

/* ── Notebook / Tabs ───────────────────────── */
notebook > header {
    background-color: alpha(@bg_color, 0.9);
    border: none;
}

notebook > header tab {
    min-height: 28px;
    padding: 4px 12px;
    color: alpha(@fg_color, 0.7);
    border: none;
    background-color: transparent;
    transition: all 120ms ease;
}

notebook > header tab:hover {
    color: @fg_color;
    background-color: alpha(@fg_color, 0.07);
}

notebook > header tab:checked {
    color: @fg_color;
    background-color: @base_color;
    box-shadow: inset 0 -2px 0 @primary_color;
}

notebook > stack {
    background-color: @base_color;
    border: none;
}

/* ── Scale / Slider ────────────────────────── */
scale {
    padding: 8px 0;
}

scale trough {
    min-height: 4px;
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.15);
}

scale highlight {
    min-height: 4px;
    border-radius: 6px;
    background-color: @primary_color;
}

scale slider {
    min-height: 16px;
    min-width: 16px;
    border-radius: 50%;
    background-color: @fg_color;
    border: none;
    margin: -6px 0;
    transition: all 120ms ease;
}

scale slider:hover {
    background-color: @primary_color;
}

scale slider:active {
    background-color: @primary_color;
    transform: scale(1.2);
}

/* ── Switch / Toggle ───────────────────────── */
switch {
    min-height: 22px;
    min-width: 44px;
    border-radius: 11px;
    background-color: alpha(@fg_color, 0.2);
    border: none;
    transition: all 120ms ease;
}

switch:checked {
    background-color: alpha(@primary_color, 0.5);
}

switch slider {
    min-height: 18px;
    min-width: 18px;
    border-radius: 50%;
    background-color: @fg_color;
    margin: 2px;
    transition: all 120ms ease;
}

switch:checked slider {
    background-color: @primary_color;
    margin-left: 24px;
}

/* ── Progress Bar ──────────────────────────── */
progressbar {
    min-height: 4px;
    border-radius: 6px;
}

progressbar trough {
    background-color: alpha(@fg_color, 0.1);
    border-radius: 6px;
}

progressbar progress {
    background-color: @primary_color;
    border-radius: 6px;
}

/* ── Scrollbars ────────────────────────────── */
scrollbar {
    background-color: transparent;
}

scrollbar.vertical {
    width: 6px;
}

scrollbar.horizontal {
    height: 6px;
}

scrollbar slider {
    background-color: alpha(@fg_color, 0.25);
    border-radius: 3px;
    min-width: 6px;
    min-height: 6px;
    transition: background-color 120ms ease;
}

scrollbar slider:hover {
    background-color: alpha(@primary_color, 0.5);
}

scrollbar slider:active {
    background-color: @primary_color;
}

scrollbar.overlay-indicator:not(.dragging):not(.hovering) {
    opacity: 0.4;
}

/* ── Menus & Popovers ──────────────────────── */
menu, .context-menu {
    background-color: alpha(@bg_color, 0.97);
    color: @fg_color;
    border: 1px solid @border_color;
    padding: 4px 0;
}

menu menuitem, modelbutton {
    min-height: 16px;
    padding: 4px 8px;
    color: @fg_color;
    transition: background-color 120ms ease;
}

menu menuitem:hover, modelbutton:hover {
    background-color: alpha(@primary_color, 0.15);
}

menu menuitem:disabled, modelbutton:disabled {
    color: alpha(@fg_color, 0.4);
}

menu separator {
    margin: 4px 0;
    background-color: @border_color;
}

menu menuitem accelerator {
    color: alpha(@fg_color, 0.6);
    margin-left: 16px;
}

popover.background {
    background-color: alpha(@bg_color, 0.97);
    color: @fg_color;
    border: 1px solid @border_color;
    border-radius: 8px;
    box-shadow: 0 2px 8px alpha(black, 0.3);
    padding: 4px 0;
}

popover.background menuitem {
    padding: 4px 8px;
}

popover.background menuitem:hover {
    background-color: alpha(@primary_color, 0.15);
}

/* ── Combobox ──────────────────────────────── */
combobox button.toggle {
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.06);
    color: @fg_color;
    border: 1px solid @border_color;
}

combobox button.toggle:hover {
    background-color: alpha(@primary_color, 0.12);
}

combobox arrow {
    -gtk-icon-source: -gtk-icontheme("pan-down-symbolic");
}

combobox cellview {
    color: @fg_color;
}

/* ── Tooltip ───────────────────────────────── */
tooltip {
    border-radius: 6px;
    background-color: alpha(@base_color, 0.95);
    color: @fg_color;
    border: 1px solid @border_color;
    padding: 4px 8px;
}

tooltip * {
    border-radius: 6px;
}

/* ── OSD ───────────────────────────────────── */
label.osd, button.osd {
    border-radius: 6px;
    background-color: alpha(@base_color, 0.9);
    color: @fg_color;
}

button.osd:hover {
    background-color: alpha(@fg_color, 0.1);
}

/* ── Flowbox ───────────────────────────────── */
flowbox flowboxchild {
    border-radius: 6px;
    padding: 3px;
    transition: background-color 120ms ease;
}

flowbox flowboxchild:selected {
    background-color: alpha(@primary_color, 0.25);
}

/* ── Expander ──────────────────────────────── */
expander arrow {
    min-width: 16px;
    min-height: 16px;
    border-radius: 6px;
}

/* ── Color Button ──────────────────────────── */
colorbutton {
    border-radius: 6px;
}

/* ── Info Bars ─────────────────────────────── */
infobar {
    border-radius: 0;
    border-style: none;
}

infobar > revealer > box {
    border-radius: 0;
}

/* ── Rubberband ────────────────────────────── */
rubberband, .rubberband,
treeview.view rubberband,
iconview rubberband,
.content-view rubberband {
    border: 1px solid alpha(@primary_color, 0.4);
    background-color: alpha(@primary_color, 0.08);
    border-radius: 0;
}

/* ── Dialog Action Area ────────────────────── */
.dialog-action-area button,
.dialog-action-box button,
window.dialog button {
    background-color: alpha(@fg_color, 0.07);
    color: @fg_color;
    border: 1px solid @border_color;
}

.dialog-action-area button:hover,
.dialog-action-box button:hover,
window.dialog button:hover {
    background-color: alpha(@primary_color, 0.12);
}

/* ── Status Bar ────────────────────────────── */
statusbar {
    background-color: alpha(@bg_color, 0.9);
    border-top: 1px solid @border_color;
    padding: 2px 6px;
    font-size: 0.9em;
}

/* ── Paned Separator ───────────────────────── */
paned > separator {
    min-width: 1px;
    min-height: 1px;
    background-color: @border_color;
    border: none;
}

paned > separator:hover {
    background-color: @primary_color;
}

/* ── Links ─────────────────────────────────── */
*:link, link {
    color: @primary_color;
}

*:visited {
    color: alpha(@primary_color, 0.7);
}

/* ── Selection (broad override) ────────────── */
*:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

*:selected:focus {
    background-color: alpha(@primary_color, 0.3);
}

/* ── Thunar Specific ───────────────────────── */
.thunar .view {
    background-color: @base_color;
    color: @fg_color;
}

.thunar .view:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

.thunar .sidebar {
    background-color: alpha(@base_color, 0.95);
}

.thunar .sidebar row:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

.thunar .sidebar row:hover {
    background-color: alpha(@fg_color, 0.07);
}

.thunar toolbar, .thunar .primary-toolbar {
    background-color: alpha(@bg_color, 0.9);
}

.thunar .statusbar {
    background-color: alpha(@bg_color, 0.9);
    color: alpha(@fg_color, 0.7);
    border-top: 1px solid @border_color;
}

.thunar .dialog-vbox {
    background-color: @base_color;
}

.thunar infobar {
    background-color: alpha(@bg_color, 0.9);
    color: @fg_color;
    border: 1px solid @border_color;
}

.thunar notebook > header tab label {
    color: alpha(@fg_color, 0.7);
}

.thunar notebook > header tab:checked label {
    color: @primary_color;
}

.thunar .view .rubberband,
.thunar iconview .rubberband {
    border: 1px solid alpha(@primary_color, 0.4);
    background-color: alpha(@primary_color, 0.08);
    border-radius: 0;
}
EOF

log "Generating GTK4 styles..."
cat > "$THEME_DIR/gtk-4.0/gtk.css" << 'EOF'
@import url("colors.css");

/* ═══════════════════════════════════════════════
   Primo GTK4 Theme — generated by rebuild_primo.sh
   ═══════════════════════════════════════════════ */

/* ── Global Reset ──────────────────────────── */
* {
    background-clip: padding-box;
    -gtk-outline-radius: 6px;
    outline-color: alpha(@fg_color, 0.15);
    outline-style: solid;
    outline-width: 0;
    outline-offset: -4px;
}

/* ── Window ────────────────────────────────── */
window.background {
    background-color: @base_color;
    color: @fg_color;
}

window.background.csd {
    border-radius: 0;
}

/* ── Base States ───────────────────────────── */
*:disabled {
    -gtk-icon-effect: dim;
    color: alpha(@fg_color, 0.4);
}

.dim-label {
    color: alpha(@fg_color, 0.6);
}

separator {
    background-color: @border_color;
}

/* ── Entries & Spinbuttons ─────────────────── */
entry, spinbutton {
    min-height: 34px;
    padding: 0 8px;
    border-radius: 6px;
    caret-color: currentColor;
    background-color: alpha(@fg_color, 0.06);
    color: @fg_color;
    border: 1px solid @border_color;
    transition: border-color 120ms ease, background-color 120ms ease;
}

entry:focus, spinbutton:focus {
    border-color: @primary_color;
    background-color: alpha(@primary_color, 0.06);
}

entry:disabled, spinbutton:disabled {
    background-color: alpha(@fg_color, 0.03);
    color: alpha(@fg_color, 0.4);
    border-color: alpha(@border_color, 0.4);
}

entry selection, spinbutton selection {
    background-color: @selected_bg_color;
    color: @selected_fg_color;
}

/* ── Buttons ───────────────────────────────── */
button {
    min-height: 24px;
    min-width: 16px;
    padding: 5px 9px;
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.07);
    color: @fg_color;
    border: 1px solid @border_color;
    transition: all 120ms ease;
}

button:hover {
    background-color: alpha(@primary_color, 0.12);
    border-color: alpha(@primary_color, 0.3);
}

button:active {
    background-color: alpha(@primary_color, 0.18);
}

button:checked {
    background-color: alpha(@primary_color, 0.25);
    color: @primary_color;
    border-color: alpha(@primary_color, 0.4);
}

button:disabled {
    background-color: alpha(@fg_color, 0.03);
    color: alpha(@fg_color, 0.4);
    border-color: alpha(@border_color, 0.3);
}

button:focus {
    border-color: @primary_color;
}

button.flat {
    background-color: transparent;
    border-color: transparent;
}

button.flat:hover {
    background-color: alpha(@fg_color, 0.07);
}

button.suggested-action {
    background-color: @primary_color;
    color: @selected_fg_color;
    border-color: @primary_color;
}

button.suggested-action:hover {
    background-color: alpha(@primary_color, 0.85);
}

button.destructive-action {
    background-color: @error_color;
    color: @selected_fg_color;
    border-color: @error_color;
}

button.destructive-action:hover {
    opacity: 0.85;
}

/* ── Linked Buttons ────────────────────────── */
.linked > button, .linked > spinbutton, .linked > entry {
    border-radius: 0;
}

.linked > button:first-child {
    border-top-left-radius: 6px;
    border-bottom-left-radius: 6px;
}

.linked > button:last-child {
    border-top-right-radius: 6px;
    border-bottom-right-radius: 6px;
}

.linked > button:only-child {
    border-radius: 6px;
}

/* ── Headerbar / Titlebar ──────────────────── */
headerbar, .titlebar {
    min-height: 40px;
    padding: 0 8px;
    background-color: alpha(@bg_color, 0.95);
    color: @fg_color;
    border-bottom: 1px solid @border_color;
}

headerbar button, .titlebar button {
    border-color: transparent;
    background-color: transparent;
}

headerbar button:hover, .titlebar button:hover {
    background-color: alpha(@fg_color, 0.1);
}

headerbar button:checked, .titlebar button:checked {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

/* ── Menu Bar ──────────────────────────────── */
.menu-bar {
    background-color: alpha(@bg_color, 0.95);
    border-bottom: 1px solid @border_color;
}

.menu-bar button {
    background: transparent;
    border: none;
    padding: 2px 8px;
    transition: background-color 120ms ease;
}

.menu-bar button:hover {
    background-color: alpha(@fg_color, 0.1);
}

/* ── Toolbar ───────────────────────────────── */
.toolbar {
    background-color: alpha(@bg_color, 0.9);
    border-bottom: 1px solid @border_color;
}

.toolbar button {
    border-radius: 6px;
    transition: all 120ms ease;
}

.toolbar button:hover {
    background-color: alpha(@primary_color, 0.12);
}

/* ── Sidebar ───────────────────────────────── */
.sidebar {
    background-color: alpha(@base_color, 0.95);
    border-right: 1px solid @border_color;
}

.sidebar .view:not(:selected):hover {
    background-color: alpha(@fg_color, 0.07);
}

.sidebar .view:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

placessidebar row {
    min-height: 28px;
    padding: 4px 8px;
    border-radius: 6px;
}

placessidebar row:hover {
    background-color: alpha(@fg_color, 0.07);
}

placessidebar row:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

/* ── Column Headers ────────────────────────── */
columnheader button {
    background-color: alpha(@bg_color, 0.8);
    border-bottom: 1px solid @border_color;
    border-right: 1px solid @border_color;
    font-weight: 600;
    border-radius: 0;
}

columnheader button:hover {
    background-color: alpha(@fg_color, 0.07);
    border-bottom-color: @primary_color;
}

/* ── Tree / List View ──────────────────────── */
treeview.view {
    background-color: @base_color;
    color: @fg_color;
}

treeview.view:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

treeview.view:not(:selected):hover {
    background-color: alpha(@fg_color, 0.05);
}

treeview.view separator {
    background-color: @border_color;
}

/* ── Icon View ─────────────────────────────── */
iconview {
    background-color: @base_color;
    color: @fg_color;
}

iconview:selected {
    background-color: alpha(@primary_color, 0.25);
}

iconview:hover:not(:selected) {
    background-color: alpha(@fg_color, 0.05);
}

/* ── Notebook / Tabs ───────────────────────── */
notebook > header {
    background-color: alpha(@bg_color, 0.9);
    border: none;
}

notebook > header tab {
    min-height: 28px;
    padding: 4px 12px;
    color: alpha(@fg_color, 0.7);
    border: none;
    background-color: transparent;
    transition: all 120ms ease;
}

notebook > header tab:hover {
    color: @fg_color;
    background-color: alpha(@fg_color, 0.07);
}

notebook > header tab:checked {
    color: @fg_color;
    background-color: @base_color;
    box-shadow: inset 0 -2px 0 @primary_color;
}

notebook > stack {
    background-color: @base_color;
    border: none;
}

/* ── Scale / Slider ────────────────────────── */
scale {
    padding: 8px 0;
}

scale trough {
    min-height: 4px;
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.15);
}

scale highlight {
    min-height: 4px;
    border-radius: 6px;
    background-color: @primary_color;
}

scale slider {
    min-height: 16px;
    min-width: 16px;
    border-radius: 50%;
    background-color: @fg_color;
    border: none;
    margin: -6px 0;
    transition: all 120ms ease;
}

scale slider:hover {
    background-color: @primary_color;
}

scale slider:active {
    background-color: @primary_color;
}

/* ── Switch / Toggle ───────────────────────── */
switch {
    min-height: 22px;
    min-width: 44px;
    border-radius: 11px;
    background-color: alpha(@fg_color, 0.2);
    border: none;
    transition: all 120ms ease;
}

switch:checked {
    background-color: alpha(@primary_color, 0.5);
}

switch slider {
    min-height: 18px;
    min-width: 18px;
    border-radius: 50%;
    background-color: @fg_color;
    margin: 2px;
    transition: all 120ms ease;
}

switch:checked slider {
    background-color: @primary_color;
}

/* ── Progress Bar ──────────────────────────── */
progressbar {
    min-height: 4px;
    border-radius: 6px;
}

progressbar trough {
    background-color: alpha(@fg_color, 0.1);
    border-radius: 6px;
}

progressbar progress {
    background-color: @primary_color;
    border-radius: 6px;
}

/* ── Scrollbars ────────────────────────────── */
scrollbar {
    background-color: transparent;
}

scrollbar.vertical {
    width: 6px;
}

scrollbar.horizontal {
    height: 6px;
}

scrollbar slider {
    background-color: alpha(@fg_color, 0.25);
    border-radius: 3px;
    min-width: 6px;
    min-height: 6px;
    transition: background-color 120ms ease;
}

scrollbar slider:hover {
    background-color: alpha(@primary_color, 0.5);
}

scrollbar slider:active {
    background-color: @primary_color;
}

/* ── Menus & Popovers ──────────────────────── */
menu {
    background-color: alpha(@bg_color, 0.97);
    color: @fg_color;
    border: 1px solid @border_color;
    padding: 4px 0;
}

menu menuitem {
    min-height: 16px;
    padding: 4px 8px;
    color: @fg_color;
    transition: background-color 120ms ease;
}

menu menuitem:hover {
    background-color: alpha(@primary_color, 0.15);
}

menu menuitem:disabled {
    color: alpha(@fg_color, 0.4);
}

menu separator {
    margin: 4px 0;
    background-color: @border_color;
}

menu menuitem accelerator {
    color: alpha(@fg_color, 0.6);
    margin-left: 16px;
}

popover.background {
    background-color: alpha(@bg_color, 0.97);
    color: @fg_color;
    border: 1px solid @border_color;
    border-radius: 8px;
    box-shadow: 0 2px 8px alpha(black, 0.3);
    padding: 4px 0;
}

popover.background menuitem {
    padding: 4px 8px;
}

popover.background menuitem:hover {
    background-color: alpha(@primary_color, 0.15);
}

/* ── Combobox ──────────────────────────────── */
combobox button.toggle {
    border-radius: 6px;
    background-color: alpha(@fg_color, 0.06);
    color: @fg_color;
    border: 1px solid @border_color;
}

combobox button.toggle:hover {
    background-color: alpha(@primary_color, 0.12);
}

combobox cellview {
    color: @fg_color;
}

/* ── Tooltip ───────────────────────────────── */
tooltip {
    border-radius: 6px;
    background-color: alpha(@base_color, 0.95);
    color: @fg_color;
    border: 1px solid @border_color;
    padding: 4px 8px;
}

tooltip * {
    border-radius: 6px;
}

/* ── OSD ───────────────────────────────────── */
label.osd, button.osd {
    border-radius: 6px;
    background-color: alpha(@base_color, 0.9);
    color: @fg_color;
}

button.osd:hover {
    background-color: alpha(@fg_color, 0.1);
}

/* ── Flowbox ───────────────────────────────── */
flowbox flowboxchild {
    border-radius: 6px;
    padding: 3px;
    transition: background-color 120ms ease;
}

flowbox flowboxchild:selected {
    background-color: alpha(@primary_color, 0.25);
}

/* ── Expander ──────────────────────────────── */
expander arrow {
    min-width: 16px;
    min-height: 16px;
    border-radius: 6px;
}

/* ── Color Button ──────────────────────────── */
colorbutton {
    border-radius: 6px;
}

/* ── Info Bars ─────────────────────────────── */
infobar {
    border-radius: 0;
    border-style: none;
}

infobar > revealer > box {
    border-radius: 0;
}

/* ── Rubberband ────────────────────────────── */
rubberband, .rubberband,
treeview.view rubberband,
iconview rubberband {
    border: 1px solid alpha(@primary_color, 0.4);
    background-color: alpha(@primary_color, 0.08);
    border-radius: 0;
}

/* ── Dialog Action Area ────────────────────── */
.dialog-action-area button,
window.dialog button {
    background-color: alpha(@fg_color, 0.07);
    color: @fg_color;
    border: 1px solid @border_color;
}

.dialog-action-area button:hover,
window.dialog button:hover {
    background-color: alpha(@primary_color, 0.12);
}

/* ── Status Bar ────────────────────────────── */
statusbar {
    background-color: alpha(@bg_color, 0.9);
    border-top: 1px solid @border_color;
    padding: 2px 6px;
}

/* ── Paned Separator ───────────────────────── */
paned > separator {
    min-width: 1px;
    min-height: 1px;
    background-color: @border_color;
    border: none;
}

paned > separator:hover {
    background-color: @primary_color;
}

/* ── Links ─────────────────────────────────── */
*:link, link {
    color: @primary_color;
}

*:visited {
    color: alpha(@primary_color, 0.7);
}

/* ── Selection (broad override) ────────────── */
*:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

*:selected:focus {
    background-color: alpha(@primary_color, 0.3);
}

/* ── Thunar Specific ───────────────────────── */
.thunar .view {
    background-color: @base_color;
    color: @fg_color;
}

.thunar .view:selected {
    background-color: alpha(@primary_color, 0.25);
    color: @fg_color;
}

.thunar .sidebar {
    background-color: alpha(@base_color, 0.95);
}

.thunar .sidebar row:selected {
    background-color: alpha(@primary_color, 0.2);
    color: @primary_color;
}

.thunar .sidebar row:hover {
    background-color: alpha(@fg_color, 0.07);
}

.thunar toolbar, .thunar .primary-toolbar {
    background-color: alpha(@bg_color, 0.9);
}

.thunar .statusbar {
    background-color: alpha(@bg_color, 0.9);
    color: alpha(@fg_color, 0.7);
    border-top: 1px solid @border_color;
}

.thunar .dialog-vbox {
    background-color: @base_color;
}

.thunar infobar {
    background-color: alpha(@bg_color, 0.9);
    color: @fg_color;
    border: 1px solid @border_color;
}

.thunar notebook > header tab label {
    color: alpha(@fg_color, 0.7);
}

.thunar notebook > header tab:checked label {
    color: @primary_color;
}

.thunar .view .rubberband,
.thunar iconview .rubberband {
    border: 1px solid alpha(@primary_color, 0.4);
    background-color: alpha(@primary_color, 0.08);
    border-radius: 0;
}
EOF

log "Copying color definitions..."
cp "$COLORS_FILE" "$THEME_DIR/gtk-3.0/colors.css"
cp "$COLORS_FILE" "$THEME_DIR/gtk-4.0/colors.css"

if command -v gtk-builder-tool &>/dev/null; then
    log "Compiling GTK resources..."
    gtk-builder-tool simplify \
        /usr/share/themes/Adwaita-dark/gtk-3.0/gtk.gresource \
        --output=$THEME_DIR/gtk-3.0/gtk.gresource 2>/dev/null || true
    gtk-builder-tool simplify \
        /usr/share/themes/Adwaita-dark/gtk-4.0/gtk.gresource \
        --output=$THEME_DIR/gtk-4.0/gtk.gresource 2>/dev/null || true
fi

log "Setting GTK theme..."
gsettings set org.gnome.desktop.interface gtk-theme "Primo"

log "Setting icon theme..."
gsettings set org.gnome.desktop.interface icon-theme "macOS"

echo "✓ Primo theme ready for Thunar"
echo "  Theme directory: $THEME_DIR"
echo "  GTK theme: Primo"
echo "  Icon theme: macOS"
