#!/usr/bin/env python3

from bluetooth import main_menu, print_status

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "--status":
        print_status()
    else:
        main_menu()
